-- Cater Vegas inventory catalog shared from admin to client.
-- Run this in Supabase SQL editor before using the live inventory module.

create table if not exists public.cater_inventory (
  id bigint generated by default as identity primary key,
  workspace_id text not null default 'cater-vegas',
  name text not null,
  category text not null default 'Tables',
  description text,
  quantity_available integer not null default 0,
  price_label text,
  image_url text,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.cater_inventory enable row level security;

create or replace function public.set_cater_inventory_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists cater_inventory_set_updated_at on public.cater_inventory;
create trigger cater_inventory_set_updated_at
before update on public.cater_inventory
for each row
execute function public.set_cater_inventory_updated_at();

drop policy if exists cater_inventory_select_workspace_access on public.cater_inventory;
create policy cater_inventory_select_workspace_access
on public.cater_inventory
for select
to authenticated
using (
  workspace_id = 'cater-vegas'
  and (
    is_active = true
    or public.beoflow_is_workspace_admin(workspace_id)
  )
);

drop policy if exists cater_inventory_insert_workspace_admin on public.cater_inventory;
create policy cater_inventory_insert_workspace_admin
on public.cater_inventory
for insert
to authenticated
with check (public.beoflow_is_workspace_admin(workspace_id));

drop policy if exists cater_inventory_update_workspace_admin on public.cater_inventory;
create policy cater_inventory_update_workspace_admin
on public.cater_inventory
for update
to authenticated
using (public.beoflow_is_workspace_admin(workspace_id))
with check (public.beoflow_is_workspace_admin(workspace_id));

drop policy if exists cater_inventory_delete_workspace_admin on public.cater_inventory;
create policy cater_inventory_delete_workspace_admin
on public.cater_inventory
for delete
to authenticated
using (public.beoflow_is_workspace_admin(workspace_id));

grant select, insert, update, delete on public.cater_inventory to authenticated;
grant usage, select on sequence public.cater_inventory_id_seq to authenticated;
